version: 2
updates:
  # ───────────── Node.js (npm/yarn) ─────────────
  - package-ecosystem: "npm"
    directory: "/"  # Root JS
    schedule: { interval: "daily" }

  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule: { interval: "daily" }

  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule: { interval: "daily" }

  - package-ecosystem: "npm"
    directory: "/apps/block_scout_web/assets"
    open-pull-requests-limit: 10
    schedule: { interval: "monthly" }
    ignore:
      - dependency-name: "bootstrap"
      - dependency-name: "web3"
        versions: ["4.x"]

  - package-ecosystem: "npm"
    directory: "/apps/explorer"
    open-pull-requests-limit: 10
    schedule: { interval: "monthly" }

  - package-ecosystem: "yarn"
    directory: "/"
    open-pull-requests-limit: 5
    schedule: { interval: "weekly" }

  # ───────────── Python (pip) ─────────────
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 5
    schedule: { interval: "weekly" }

  - package-ecosystem: "pip"
    directory: "/packages/api"
    schedule: { interval: "weekly" }

  # ───────────── Rust (cargo) ─────────────
  - package-ecosystem: "cargo"
    directory: "/packages/rust"
    schedule: { interval: "weekly" }

  # ───────────── Java (maven) ─────────────
  - package-ecosystem: "maven"
    directory: "/packages/java"
    schedule: { interval: "weekly" }

  # ───────────── Docker ─────────────
  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 20
    schedule: { interval: "weekly" }

  # ───────────── GitHub Actions ─────────────
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }

  - package-ecosystem: "github-actions"
    directory: "/contracts"
    schedule: { interval: "weekly" }
