github.com:
    users:
        koagonzalo11:
            oauth_token: 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
        "":
            oauth_token: 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
    git_protocol: ssh
    user:
    oauth_token: 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
